server:
  port: 8080

#  datasource:
#    url: 'jdbc:postgresql://localhost:5432/test?ApplicationName=MultiTenantSupport'
#    username: 'postgres'
#    password: 'postgres'
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: none

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/multitenant?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: dbuser
    password: dbuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        session_factory:
          interceptor: com.example.interceptor.ShardingInterceptor



  application:
    name: MultiTenantSupport
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace